### ISSUE TITLE
I WANT THE FUKN THING FOR FREE

### ISSUE THREAD

**Issue by nscwalk** [Aventium/HCFactions#1]
YOU MOTHER FUCKING SON OF A BITCH just give it to me already I swear 2 god I will kms.......... jk but you get the point I want te fkn plgn

**Comment by Aventium** [comment]
I haven't even started on it, chill bud.

**Comment by nscwalk** [comment]
YOU SHOULD GIVE ME THE ONE YOU ALREADY HAVE
